### ISSUE TITLE
Add Pausing and Resuming at a certain percent in a Level.

### ISSUE THREAD

**Issue by AlwaysJolly** [Vinsterplays/Music-Integrations#1]
As the name suggests, I think it'd be cool the add a feature which, in practice, works sorta like Auto Deafen, letting you set a percent which will pause media once reached.

I, as a player, have personally wanted a mod that does this for a while now, so I think it would be incredibly useful.

**Comment by Vinsterplays** [comment]
if other people are interested in a feature like this I dont see why not

**Comment by AlwaysJolly** [comment]
I know at least a few of my friends would greatly appreciate this feature, I don't know how hard it'd be to add but I'm sure people would greatly appreciate it. I often play levels with YouTube on and I think it'd be really useful if I could have something to pause it when I'm far.

**Comment by Toiweon** [comment]
I'd be cool

**Comment by Kevgmd** [comment]
This mod are the proof of why mods are so important on a game, super convenient, i always like to play while listening to music, would be even better if the song just didnt pause when entering a level and the game music is muted, and then play when the music is set to muted on the pause screen.

**Comment by Vinsterplays** [comment]
Added in 1.2.0
