### ISSUE TITLE
Extra toggle cases

### ISSUE THREAD

**Issue by natopotato390** [Vinsterplays/Music-Integrations#3]
Awesome mod! love listening to Spotify while level building so this is perfect. 

A few areas some new cases could be added, first and most importantly:
*-When playtesting a level (using "Save and Play") and hitting the level editor button in the pause menu, playback does not resume.*

Rest of these play overlapping music, and could be tricky to implement/up to user preference...
*-The music playtest button in the editor, all the music play buttons in the music library.*
*-Record guidelines tool. bpm tool. Sound Effects?*
*-All Vault rooms, and The Tower music*

**Comment by Vinsterplays** [comment]
Added toggle cases for the playtest button, music library, and bpm tool in 1.2.0. Vaults and The Tower will come later
