### ISSUE TITLE
The mod makes the game freeze every time it is supposed to pause the music.

### ISSUE THREAD

**Issue by Akurio64** [Vinsterplays/Music-Integrations#5]
One day as I was gonna work on a level, and as soon as I clicked the editor button, the game crashed. I troubleshooted every mod and it happens only with SpotifyConnect. It also happens when I click the play button, so I assume it happens because some error related to pausing the music. 

It randomly happens from time to time. If I force-close the game and try again, it will still freeze. The solution to stop this from happening is to restart the computer. There is no crash log as the game freezes. All I know is that in the console, it gives a libpng error. Furthermore, I noticed that when it happens, any UWP software that I open freezes the taskbar, so this might be a problem coming from me.

**Comment by Vinsterplays** [comment]
has anyone else encountered this? There isnt much information here for me to find the issue

**Comment by Vinsterplays** [comment]
Issue was caused by a windows issue stopping the media keys from functioning. Fixed the crash but the mod will not work unless you restart your computer
